try {
  let a = 10;
  console.log("number", a);
  console.logs(a);
} catch (error) {
  console.log(error);
}
